name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '50 4 * * *'

env:
  rust_toolchain: stable

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_toolchain }}
          components: rustfmt, clippy
      - name: Build | Fmt Check
        run: cargo fmt -- --check
      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: Build | Clippy
        run: cargo clippy --no-deps --target wasm32-unknown-unknown -- -Dwarnings
      - name: Build | Compile
        run: cargo build --target wasm32-unknown-unknown
